BEGIN;

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('users', 'id', 'Код'),
    ('users', 'name', 'Имя'),
    ('users', 'role_id', 'Роль'),
    ('users', 'email', 'Электронная почта'),
    ('users', 'pwd', 'Пароль'),
    ('users', 'tel_ext', 'Внутренний телефон'),
    ('users', 'phone_cel', 'Сотовый телефон'),
    ('users', 'create_dt', 'Дата создания'),
    ('users', 'banned', 'Заблокирован'),
    ('users', 'time_zone_locale_id', 'Часовой пояс'),
    ('users', 'production_site_id', 'Производственная площадка'),
    ('users', 'elkon_user_name', 'Не используется, используется справочник user_map_to_production'),
    ('users', 'domru_user_name', 'Для облачной АТС'),
    ('users', 'params', 'Параметры');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('destinations', 'id', 'Код'),
    ('destinations', 'name', 'Наименование'),
    ('destinations', 'distance', 'Расстояние'),
    ('destinations', 'time_route', 'Время'),
    ('destinations', 'price', 'Стоимость'),
    ('destinations', 'zone', 'Зона'),
    ('destinations', 'special_price', 'Специальная цена'),
    ('destinations', 'price_for_driver', 'Цена для водителя'),
    ('destinations', 'near_road_lon', 'Долгота ближайшей дороги'),
    ('destinations', 'near_road_lat', 'Широта ближайшей дороги'),
    ('destinations', 'send_route_sms', 'Отправлять СМС с маршрутом');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('concrete_types', 'id', 'Код'),
    ('concrete_types', 'name', 'Наименование'),
    ('concrete_types', 'code_1c', 'Код 1С'),
    ('concrete_types', 'pres_norm', 'Норма давл.'),
    ('concrete_types', 'mpa_ratio', 'Кф.МПА'),
    ('concrete_types', 'price', 'Цена'),
    ('concrete_types', 'material_cons_rates', 'Есть нормы расхода'),
    ('concrete_types', 'show_on_site', 'Отображать на сайте'),
    ('concrete_types', 'official_name', 'Официальное наименование для накладной'),
    ('concrete_types', 'prochnost', 'Прочность для паспорта качества'),
    ('concrete_types', 'f_val', 'F'),
    ('concrete_types', 'w_val', 'W');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('vehicle_owners', 'id', 'Код'),
    ('vehicle_owners', 'name', 'Наименование'),
    ('vehicle_owners', 'user_id', 'Пользователь'),
    ('vehicle_owners', 'client_id', 'Клиент');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('pump_vehicles', 'id', 'Код'),
    ('pump_vehicles', 'vehicle_id', 'Автомобиль'),
    ('pump_vehicles', 'pump_price_id', 'Цена автобетононасоса'),
    ('pump_vehicles', 'phone_cel', 'Сотовый телефон'),
    ('pump_vehicles', 'pump_length', 'Длина стрелы'),
    ('pump_vehicles', 'deleted', 'Удален'),
    ('pump_vehicles', 'comment_text', 'Комментарий'),
    ('pump_vehicles', 'phone_cels', 'Сотовые телефоны (JSON)'),
    ('pump_vehicles', 'pump_prices', 'Цены насосов (JSON)'),
    ('pump_vehicles', 'specialist_inform', 'Информировать специалиста'),
    ('pump_vehicles', 'driver_ship_inform', 'Информировать водителя об отгрузке'),
    ('pump_vehicles', 'min_order_quant', 'Минимальное количество м3 для заявки'),
    ('pump_vehicles', 'min_order_time_interval', 'Минимальный интервал между заявками');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('employees', 'id', 'Код'),
    ('employees', 'name', 'ФИО'),
    ('employees', 'employed', 'Работает'),
    ('employees', 'user_id', 'Пользователь'),
    ('employees', 'inn', 'ИНН'),
    ('employees', 'post', 'Должность');

INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('vehicles', 'id', 'Код'),
    ('vehicles', 'plate', 'Номер'),
    ('vehicles', 'plate_region', 'Регин номера'),
    ('vehicles', 'plate_n', 'Номер число для сортировки'),
    ('vehicles', 'load_capacity', 'Грузоподъемность'),
    ('vehicles', 'make', 'Марка'),
    ('vehicles', 'driver_id', 'Водитель'),
    ('vehicles', 'feature', 'Свойство'),
    ('vehicles', 'tracker_id', 'Трэкер'),
    ('vehicles', 'sim_id', 'Идентификатор SIM карты'),
    ('vehicles', 'sim_number', 'Номер телефона SIM карты'),
    ('vehicles', 'vehicle_owner_id', 'УДАЛИТЬ Владелец'),
    ('vehicles', 'vehicle_owners', 'История владелецев'),
    ('vehicles', 'vehicle_owners_ar', 'Владельцы (массив)'),
    ('vehicles', 'ord_num', 'Порядковый номер'),
    ('vehicles', 'weight_t', 'Масса, тонн'),
    ('vehicles', 'vin', 'VIN'),
    ('vehicles', 'leasor', 'Leasor name'),
    ('vehicles', 'leasing_contract_date', 'Дата договора лизинга'),
    ('vehicles', 'leasing_contract_num', 'Номер договора лизинга'),
    ('vehicles', 'leasing_total', 'Общая сумма лизинга'),
    ('vehicles', 'insurance_osago', 'Insurance osago data'),
    ('vehicles', 'insurance_kasko', 'Insurance kasko data'),
    ('vehicles', 'official_vehicle_owner_id', 'УДАЛИТЬ Владелец');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('cement_silo_balance_resets', 'id', 'Код'),
    ('cement_silo_balance_resets', 'date_time', 'Дата и время'),
    ('cement_silo_balance_resets', 'user_id', 'Пользователь'),
    ('cement_silo_balance_resets', 'cement_silo_id', 'Цементный силос'),
    ('cement_silo_balance_resets', 'comment_text', 'Комментарий'),
    ('cement_silo_balance_resets', 'quant_required', 'Требуемое количество');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('doc_material_movements', 'id', 'Код'),
    ('doc_material_movements', 'date_time', 'Дата'),
    ('doc_material_movements', 'processed', 'Проведен'),
    ('doc_material_movements', 'number', 'Номер'),
    ('doc_material_movements', 'material_id', 'Материал'),
    ('doc_material_movements', 'production_base_from_id', 'Производственная база (откуда)'),
    ('doc_material_movements', 'production_base_to_id', 'Производственная база (куда)'),
    ('doc_material_movements', 'quant', 'Количество'),
    ('doc_material_movements', 'user_id', 'Автор'),
    ('doc_material_movements', 'carrier_id', 'Carrier'),
    ('doc_material_movements', 'vehicle_plate', 'Vehicle plate'),
    ('doc_material_movements', 'last_modif_user_id', 'Кто последний вносил изменения'),
    ('doc_material_movements', 'last_modif_date_time', 'Время последнего изменения'),
    ('doc_material_movements', 'comment_text', 'Комментарий');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('doc_material_procurements', 'id', 'Код'),
    ('doc_material_procurements', 'date_time', 'Дата'),
    ('doc_material_procurements', 'process_date_time', 'Дата обработки'),
    ('doc_material_procurements', 'number', 'Номер'),
    ('doc_material_procurements', 'doc_ref', 'Ссылка на документ'),
    ('doc_material_procurements', 'processed', 'Проведен'),
    ('doc_material_procurements', 'user_id', 'Автор'),
    ('doc_material_procurements', 'supplier_id', 'Поставщик'),
    ('doc_material_procurements', 'carrier_id', 'Перевозчик'),
    ('doc_material_procurements', 'driver', 'Водитель'),
    ('doc_material_procurements', 'vehicle_plate', 'гос.номер'),
    ('doc_material_procurements', 'material_id', 'Материал'),
    ('doc_material_procurements', 'cement_silos_id', 'Силос'),
    ('doc_material_procurements', 'quant_gross', 'Брутто'),
    ('doc_material_procurements', 'quant_net', 'Нетто'),
    ('doc_material_procurements', 'store', 'Склад'),
    ('doc_material_procurements', 'sender_name', 'Отправитель'),
    ('doc_material_procurements', 'production_base_id', 'База'),
    ('doc_material_procurements', 'doc_quant_gross', 'Брутто по документам'),
    ('doc_material_procurements', 'doc_quant_net', 'Нетто по документам'),
    ('doc_material_procurements', 'comment_text', 'Комментарий'),
    ('doc_material_procurements', 'last_modif_user_id', 'Кто последний вносил изменения'),
    ('doc_material_procurements', 'last_modif_date_time', 'Время последнего изменения'),
    ('doc_material_procurements', 'weigh_app', 'Приложение для взвешивания');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('shipments', 'id', 'Код'),
    ('shipments', 'date_time', 'Дата'),
    ('shipments', 'order_id', 'Заявка'),
    ('shipments', 'vehicle_schedule_id', 'Экипаж'),
    ('shipments', 'quant', 'Количество'),
    ('shipments', 'user_id', 'Автор'),
    ('shipments', 'production_site_id', 'Завод'),
    ('shipments', 'client_mark', 'Баллы'),
    ('shipments', 'demurrage', 'Простой'),
    ('shipments', 'blanks_exist', 'Наличие бланков'),
    ('shipments', 'owner_agreed', 'Согласовано владельцем'),
    ('shipments', 'owner_agreed_date_time', 'Дата согласования владельцем'),
    ('shipments', 'acc_comment', 'Комментарий бухгалтера'),
    ('shipments', 'acc_comment_shipment', 'Комментарий бухгалтера по отгрузке'),
    ('shipments', 'owner_pump_agreed', 'Согласовано владельцем насоса'),
    ('shipments', 'owner_pump_agreed_date_time', 'Дата согласования владельцем насоса'),
    ('shipments', 'pump_cost', 'Стоимость насоса'),
    ('shipments', 'pump_cost_edit', 'Редактирование стоимости насоса'),
    ('shipments', 'ship_cost', 'Стоимость доставки'),
    ('shipments', 'ship_cost_edit', 'Редактирование стоимости доставки'),
    ('shipments', 'pump_for_client_cost', 'Стоимость насоса для клиента'),
    ('shipments', 'pump_for_client_cost_edit', 'Редактирование стоимости насоса для клиента');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('orders', 'id', 'Код'),
    ('orders', 'client_id', 'клиент'),
    ('orders', 'destination_id', 'Направление'),
    ('orders', 'concrete_type_id', 'Марка бетона'),
    ('orders', 'unload_type', 'Прокачка'),
    ('orders', 'comment_text', 'Комментарий'),
    ('orders', 'descr', 'Описание'),
    ('orders', 'date_time', 'Дата'),
    ('orders', 'date_time_to', 'Время до'),
    ('orders', 'quant', 'Количество'),
    ('orders', 'phone_cel', 'Сот.телефон'),
    ('orders', 'unload_speed', 'Разгрузка куб/ч'),
    ('orders', 'user_id', 'Автор'),
    ('orders', 'lang_id', 'Язык'),
    ('orders', 'total', 'Сумма'),
    ('orders', 'concrete_price', 'Стоимость'),
    ('orders', 'destination_price', 'Стоимость дост.'),
    ('orders', 'unload_price', 'Стоимость прокачки'),
    ('orders', 'pump_vehicle_id', 'Насос'),
    ('orders', 'pay_cash', 'Оплата на месте'),
    ('orders', 'total_edit', 'Редактирование суммы'),
    ('orders', 'payed', 'Оплачено'),
    ('orders', 'under_control', 'Под контролем'),
    ('orders', 'last_modif_user_id', 'Кто последний вносил изменения'),
    ('orders', 'last_modif_date_time', 'Время последнего изменения'),
    ('orders', 'create_date_time', 'Время создания'),
    ('orders', 'ext_production', 'Для другого завода'),
    ('orders', 'contact_id', 'Контакт'),
    ('orders', 'client_specification_id', 'Спецификация'),
    ('orders', 'f_val', 'F'),
    ('orders', 'w_val', 'W');
INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('material_fact_consumption_corrections', 'id', 'Код'),
    ('material_fact_consumption_corrections', 'production_site_id', 'Производственная площадка'),
    ('material_fact_consumption_corrections', 'date_time', 'Дата и время'),
    ('material_fact_consumption_corrections', 'date_time_set', 'Дата и время установки'),
    ('material_fact_consumption_corrections', 'user_id', 'Пользователь'),
    ('material_fact_consumption_corrections', 'material_id', 'Материал'),
    ('material_fact_consumption_corrections', 'cement_silo_id', 'Цементный силос'),
    ('material_fact_consumption_corrections', 'production_id', 'ID производства'),
    ('material_fact_consumption_corrections', 'elkon_id', 'ID Elkon'),
    ('material_fact_consumption_corrections', 'quant', 'Количество'),
    ('material_fact_consumption_corrections', 'comment_text', 'Комментарий');
COMMIT;
