BEGIN;

-- 1. Drop primary key constraint
ALTER TABLE public.fuel_transactions
DROP CONSTRAINT fuel_transactions_pkey;

-- 2. Drop old text id column
ALTER TABLE public.fuel_transactions
DROP COLUMN id;

-- 3. Add new auto-increment column
ALTER TABLE public.fuel_transactions
ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;

-- 4. Recreate primary key
ALTER TABLE public.fuel_transactions
ADD CONSTRAINT fuel_transactions_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX fuel_transactions_transaction_id_idx
ON public.fuel_transactions (transaction_id);

COMMIT;
