INSERT INTO audit_column_aliases (table_name, column_name, column_alias) VALUES
    ('clients', 'id', 'Код'),
    ('clients', 'name', 'Наименование'),
    ('clients', 'name_full', 'Полное наименование'),
    ('clients', 'phone_cel', 'Сотовый телефон'),
    ('clients', 'manager_comment', 'Комментарий'),
    ('clients', 'client_type_id', 'Вид контрагента'),
    ('clients', 'client_kind', 'Тип контрагента'),
    ('clients', 'client_come_from_id', 'Источник обращения'),
    ('clients', 'manager_id', 'Менеджер'),
    ('clients', 'create_date', 'Дата сооздания'),
    ('clients', 'email', 'Эл.поочта'),
    ('clients', 'inn', 'ИНН'),
    ('clients', 'kpp', 'КПП'),
    ('clients', 'address_legal', 'Адрес юридический'),
    ('clients', 'address_fact', 'Адрес фактический'),
    ('clients', 'tels_1c', 'Телефон 1с'),
    ('clients', 'user_id', 'Аккаунт'),
    ('clients', 'account_from_date', 'Дата начала выборки данных'),
    ('clients', 'bank_bik', 'БИК банка'),
    ('clients', 'bank_account', 'Банковский счет'),
    ('clients', 'ref_1c', 'Ссылка на справочник 1с'),
    ('clients', 'shipment_quant_for_cost', 'Кол отгрузки для расчета стооимости');
